<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-688SGPSJ" failures="1" tests="12" name="com.testng.TestNG" time="0.038" errors="0" timestamp="2024-12-19T10:36:40 IST" skipped="1">
  <testcase classname="com.testng.TestNG" name="sample_1" time="0.015"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_2" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_4" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_5" time="0.003"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_6" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_7" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_8" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_9" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_10" time="0.008">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.testng.TestNG.sample_10(TestNG.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- sample_10 -->
  <system-out/>
  <testcase classname="com.testng.TestNG" name="sample_3">
    <skipped/>
  </testcase> <!-- sample_3 -->
  <system-out/>
</testsuite> <!-- com.testng.TestNG -->
